from copy import copy,deepcopy
tuple1=('hello','world','I','am',456,78,[],'try',[])
print (tuple1)
tuple2=copy(tuple1)
print (tuple2)
tuple1[6].append(600)
print (tuple1)
print (tuple2)
tuple3=deepcopy(tuple1)
tuple1[8].append(800)
print (tuple1)
print (tuple2)
print (tuple3)
